name = "tg-bot"
main = "packages/worker/src/worker.ts"

workers_dev = true
compatibility_date = "2024-11-11"


[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "llama2"
database_id = "98d68b4d-0db5-4bac-bd17-4ed24a023ced"
